export type NftItem = {
  id: string;
  name: string;
  slug: string;
  description: string;
  mediaUrl: string;
  mediaType: "image" | "video";
  price: number | null;
  currency: string;
  editionType: "1/1" | "limited" | "open";
  editionsTotal: number | null;
  editionsRemaining: number | null;
  status: "available" | "sold" | "coming-soon";
  marketplaceName: string | null;
  marketplaceUrl: string | null;
  isPublished: boolean;
  order: number;
  createdAt: string | null;
  updatedAt: string | null;
};