export const CLOUDINARY_ROOT_FOLDER = "hm_visuals";

export const CLOUDINARY_MEDIA_FOLDER = `${CLOUDINARY_ROOT_FOLDER}/media`;
export const CLOUDINARY_PEOPLE_FOLDER = `${CLOUDINARY_ROOT_FOLDER}/people`;
export const CLOUDINARY_SERVICES_FOLDER = `${CLOUDINARY_ROOT_FOLDER}/services`;
export const CLOUDINARY_TESTIMONIALS_FOLDER = `${CLOUDINARY_ROOT_FOLDER}/testimonials`;

export const CLOUDINARY_MANAGED_FOLDERS = [
  CLOUDINARY_MEDIA_FOLDER,
  CLOUDINARY_PEOPLE_FOLDER,
  CLOUDINARY_SERVICES_FOLDER,
  CLOUDINARY_TESTIMONIALS_FOLDER,
] as const;